# Generated by Django 5.1.2 on 2024-11-02 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='aboutusimage/')),
                ('descriptions', models.TextField()),
                ('personimage', models.ImageField(upload_to='personimage/')),
                ('nameperson', models.CharField(max_length=100)),
                ('profession', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='homeimage/')),
                ('title', models.CharField(max_length=100)),
                ('video_file', models.FileField(upload_to='videos/')),
                ('exams', models.TextField()),
                ('examsimage', models.ImageField(upload_to='examsimage/')),
            ],
        ),
        migrations.CreateModel(
            name='StudyAbroad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='image/')),
            ],
        ),
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('company', models.CharField(max_length=100)),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Platform.home')),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('higher', models.CharField(choices=[('Secondary Educations', 'Secondary Educations'), ('Higher Educations', 'Higher Educations'), ('Language courses for youth', 'Language courses for youth'), ('Children language camps', 'Children language camps')], max_length=100)),
                ('specializations', models.CharField(choices=[('IT Technologies', 'IT Technologies'), ('Business', 'Business'), ('Medicine', 'Medicine'), ('International Relationship', 'International Relationship'), ('Tourism', 'Tourism')], max_length=100)),
                ('countrys', models.CharField(choices=[('America', 'America'), ('Germany', 'Germany'), ('Austria', 'Austria'), ('Italy', 'Italy'), ('Spain', 'Spain'), ('Greate Britain', 'Greate Britain'), ('China', 'China'), ('Latvia', 'Latvia'), ('Indonesia', 'Indonesia'), ('Holland', 'Holland'), ('Ireland', 'Ireland'), ('Cyprus', 'Cyprus'), ('Canada', 'Canada')], max_length=100)),
                ('image', models.ImageField(upload_to='countryimage/')),
                ('studyabroad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Platform.studyabroad')),
            ],
        ),
    ]
