# Generated by Django 5.1.2 on 2024-11-11 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='aboutusimage/')),
                ('descriptions', models.TextField()),
                ('descriptions_ru', models.TextField(null=True)),
                ('descriptions_en', models.TextField(null=True)),
                ('personimage', models.ImageField(blank=True, null=True, upload_to='personimage/')),
                ('nameperson', models.CharField(max_length=100)),
                ('nameperson_ru', models.CharField(max_length=100, null=True)),
                ('nameperson_en', models.CharField(max_length=100, null=True)),
                ('profession', models.CharField(max_length=200)),
                ('profession_ru', models.CharField(max_length=200, null=True)),
                ('profession_en', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('firstname_ru', models.CharField(max_length=100, null=True)),
                ('firstname_en', models.CharField(max_length=100, null=True)),
                ('lastname', models.CharField(max_length=100)),
                ('lastname_ru', models.CharField(max_length=100, null=True)),
                ('lastname_en', models.CharField(max_length=100, null=True)),
                ('phone', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=250)),
                ('company', models.CharField(choices=[('Group', 'Group'), ('Company', 'Company')], max_length=100)),
                ('company_ru', models.CharField(choices=[('Group', 'Group'), ('Company', 'Company')], max_length=100, null=True)),
                ('company_en', models.CharField(choices=[('Group', 'Group'), ('Company', 'Company')], max_length=100, null=True)),
                ('help', models.TextField()),
                ('help_ru', models.TextField(null=True)),
                ('help_en', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('name_ru', models.CharField(max_length=100, null=True)),
                ('name_en', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('description_ru', models.TextField(null=True)),
                ('description_en', models.TextField(null=True)),
                ('name', models.CharField(max_length=100)),
                ('name_ru', models.CharField(max_length=100, null=True)),
                ('name_en', models.CharField(max_length=100, null=True)),
                ('phone', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='homeimage/')),
                ('title', models.CharField(max_length=100)),
                ('title_ru', models.CharField(max_length=100, null=True)),
                ('title_en', models.CharField(max_length=100, null=True)),
                ('video_file', models.FileField(blank=True, null=True, upload_to='videos/')),
                ('exams', models.TextField()),
                ('exams_ru', models.TextField(null=True)),
                ('exams_en', models.TextField(null=True)),
                ('examsimage', models.ImageField(blank=True, null=True, upload_to='examsimage/')),
            ],
        ),
        migrations.CreateModel(
            name='StudyAbroad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('description_ru', models.TextField(null=True)),
                ('description_en', models.TextField(null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='image/')),
            ],
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100)),
                ('time', models.CharField(max_length=100)),
                ('typeofprogramis', models.TextField()),
                ('language', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('name_ru', models.CharField(max_length=100, null=True)),
                ('name_en', models.CharField(max_length=100, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='universityimage/')),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('cost', models.TextField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='image/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Platform.country')),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('name_ru', models.CharField(max_length=100, null=True)),
                ('name_en', models.CharField(max_length=100, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='facultyimage/')),
                ('description', models.TextField()),
                ('description_ru', models.TextField(null=True)),
                ('description_en', models.TextField(null=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Platform.country')),
                ('studyabroad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Platform.studyabroad')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Platform.university')),
            ],
        ),
    ]
