# Generated by Django 5.1.2 on 2024-11-02 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Platform', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contacts',
            name='home',
        ),
        migrations.AddField(
            model_name='contacts',
            name='help',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
