# Generated by Django 5.1.2 on 2024-11-08 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Platform', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutus',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='aboutusimage/'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='personimage',
            field=models.ImageField(blank=True, null=True, upload_to='personimage/'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='email',
            field=models.EmailField(max_length=250),
        ),
        migrations.AlterField(
            model_name='country',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='countryimage/'),
        ),
        migrations.AlterField(
            model_name='home',
            name='examsimage',
            field=models.ImageField(blank=True, null=True, upload_to='examsimage/'),
        ),
        migrations.AlterField(
            model_name='home',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='homeimage/'),
        ),
        migrations.AlterField(
            model_name='home',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
        migrations.AlterField(
            model_name='studyabroad',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image/'),
        ),
    ]
